---
- name: Deploy Docker containers for LAMP stack
  hosts: all
  become: yes  # Ensure superuser privileges for all tasks
  vars:
    ansible_distribution_release: "jammy"
    docker_network_name: "lamp_network"  # Define a variable for the Docker network name

  tasks:
    - name: Update the APT package index
      apt:
        update_cache: yes
        allow_unauthenticated: yes

    - name: Ensure old version of Docker is not installed
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker network for LAMP containers
      docker_network:
        name: "{{ docker_network_name }}"
        driver: bridge

    - name: Deploy MySQL container
      docker_container:
        name: lamp_mysql
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: mypassword
          MYSQL_DATABASE: mydatabase
        networks:
          - name: "{{ docker_network_name }}"

    - name: Deploy Apache container
      docker_container:
        name: lamp_apache
        image: httpd
        ports:
          - "80:80"
        volumes:
          - "/var/www/html:/usr/local/apache2/htdocs"
        networks:
          - name: "{{ docker_network_name }}"
        depends_on:
          - lamp_mysql

    - name: Deploy PHP container
      docker_container:
        name: lamp_php
        image: php:apache
        volumes:
          - "/var/www/html:/var/www/html"
        networks:
          - name: "{{ docker_network_name }}"
        depends_on:
          - lamp_apache

    - name: Create and start other containers
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "{{ item.port }}"
        networks:
          - name: "{{ docker_network_name }}"
      loop:
        - { name: "nginx", image: "nginx:latest", port: "80" }
        - { name: "mysql", image: "mysql:latest", port: "3306" }
        - { name: "apache", image: "httpd:latest", port: "8080" }
        - { name: "phpmyadmin", image: "phpmyadmin:latest", port: "80" }


deploy